  
version: "3"

services:
  eris-docs-bot:
    container_name: eris-docs-bot
    image: ghcr.io/donovandmc/eris-docs-bot
    volumes:
      - ./data:/data:z
      - ./config.json:/app/config.json
    restart: always
    healthcheck:
      interval: 10s
      timeout: 2s
      test: lsof -i :80 || exit 1
    hostname: eris-docs-bot.containers.local
    deploy:
        resources:
          limits:
            memory: 256M
          reservations:
            memory: 128M
    networks:
      default:
        ipv4_address: 172.19.3.10

networks:
  default:
    name: eris-docs-bot
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.3.8/30
          gateway: 172.19.3.9

volumes:
  modules: null
